"""Added direcotry tree

Revision ID: 30d6d4ce2c26
Revises: c325da41ace0
Create Date: 2023-04-17 23:04:25.664153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d6d4ce2c26'
down_revision = 'c325da41ace0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_foam_sim_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dir_tree', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_foam_sim_data', schema=None) as batch_op:
        batch_op.drop_column('dir_tree')

    # ### end Alembic commands ###
