"""blockmeshtable table

Revision ID: 35861f3045b6
Revises: d9a79558e95e
Create Date: 2023-02-12 22:27:48.674177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35861f3045b6'
down_revision = 'd9a79558e95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_mesh_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('mesh_dict', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('block_mesh_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_mesh_model_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_mesh_model_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_mesh_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_mesh_model_name'))
        batch_op.drop_index(batch_op.f('ix_block_mesh_model_description'))

    op.drop_table('block_mesh_model')
    # ### end Alembic commands ###
