""" Added new columns to the db

Revision ID: 3fa2d444ebe1
Revises: 6e3540639056
Create Date: 2023-03-11 14:17:08.991714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa2d444ebe1'
down_revision = '6e3540639056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_foam_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_validated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_foam_data', schema=None) as batch_op:
        batch_op.drop_column('is_validated')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
