"""empty message

Revision ID: 6b1ea4d1bfb7
Revises: 35861f3045b6
Create Date: 2023-02-18 13:21:10.893442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1ea4d1bfb7'
down_revision = '35861f3045b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_foam_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('dict_class', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('dict_data', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('open_foam_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_open_foam_data_name'), ['name'], unique=True)

    with op.batch_alter_table('block_mesh_model', schema=None) as batch_op:
        batch_op.drop_index('ix_block_mesh_model_description')
        batch_op.drop_index('ix_block_mesh_model_name')

    op.drop_table('block_mesh_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_mesh_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=120), nullable=True),
    sa.Column('mesh_dict', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('block_mesh_model', schema=None) as batch_op:
        batch_op.create_index('ix_block_mesh_model_name', ['name'], unique=False)
        batch_op.create_index('ix_block_mesh_model_description', ['description'], unique=False)

    with op.batch_alter_table('open_foam_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_open_foam_data_name'))

    op.drop_table('open_foam_data')
    # ### end Alembic commands ###
