"""empty message

Revision ID: 6e3540639056
Revises: 6b1ea4d1bfb7
Create Date: 2023-02-18 17:01:18.943703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3540639056'
down_revision = '6b1ea4d1bfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_foam_data', schema=None) as batch_op:
        batch_op.drop_index('ix_open_foam_data_name')
        batch_op.create_index(batch_op.f('ix_open_foam_data_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_foam_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_open_foam_data_name'))
        batch_op.create_index('ix_open_foam_data_name', ['name'], unique=False)

    # ### end Alembic commands ###
