"""Changed db columns for naming convetion

Revision ID: bc495c4e6a0d
Revises: 3fa2d444ebe1
Create Date: 2023-03-11 17:38:33.407480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc495c4e6a0d'
down_revision = '3fa2d444ebe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_foam_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('fdata', sa.Text(), nullable=True))
        batch_op.drop_index('ix_open_foam_data_name')
        batch_op.create_index(batch_op.f('ix_open_foam_data_fname'), ['fname'], unique=False)
        batch_op.drop_column('name')
        batch_op.drop_column('dict_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_foam_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dict_data', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_open_foam_data_fname'))
        batch_op.create_index('ix_open_foam_data_name', ['name'], unique=False)
        batch_op.drop_column('fdata')
        batch_op.drop_column('fname')

    # ### end Alembic commands ###
