"""Added new table

Revision ID: c325da41ace0
Revises: bc495c4e6a0d
Create Date: 2023-04-11 09:06:50.894091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c325da41ace0'
down_revision = 'bc495c4e6a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_foam_dict_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dict_class', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('fdata', sa.Text(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('open_foam_dict_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_open_foam_dict_data_fname'), ['fname'], unique=False)

    op.create_table('open_foam_sim_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('fdata', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('open_foam_sim_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_open_foam_sim_data_fname'), ['fname'], unique=False)

    with op.batch_alter_table('open_foam_data', schema=None) as batch_op:
        batch_op.drop_index('ix_open_foam_data_fname')

    op.drop_table('open_foam_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_foam_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dict_class', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=120), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('is_validated', sa.BOOLEAN(), nullable=True),
    sa.Column('fname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('fdata', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('open_foam_data', schema=None) as batch_op:
        batch_op.create_index('ix_open_foam_data_fname', ['fname'], unique=False)

    with op.batch_alter_table('open_foam_sim_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_open_foam_sim_data_fname'))

    op.drop_table('open_foam_sim_data')
    with op.batch_alter_table('open_foam_dict_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_open_foam_dict_data_fname'))

    op.drop_table('open_foam_dict_data')
    # ### end Alembic commands ###
