"""Initial migration

Revision ID: d6da6f63a7b9
Revises: 
Create Date: 2023-04-29 18:18:43.281720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6da6f63a7b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('open_foam_dict_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dict_class', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('fdata', sa.Text(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('open_foam_dict_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_open_foam_dict_data_fname'), ['fname'], unique=False)

    op.create_table('open_foam_sim_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('fdata', sa.LargeBinary(), nullable=True),
    sa.Column('dir_tree', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('open_foam_sim_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_open_foam_sim_data_fname'), ['fname'], unique=False)

    op.create_table('simulation_history_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('run_date', sa.DateTime(), nullable=True),
    sa.Column('results', sa.LargeBinary(), nullable=True),
    sa.Column('sim_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sim_id'], ['open_foam_sim_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_history_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_history_data_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_history_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_history_data_id'))

    op.drop_table('simulation_history_data')
    with op.batch_alter_table('open_foam_sim_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_open_foam_sim_data_fname'))

    op.drop_table('open_foam_sim_data')
    with op.batch_alter_table('open_foam_dict_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_open_foam_dict_data_fname'))

    op.drop_table('open_foam_dict_data')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
