#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove surface


cleanCase

rm -f 0/Ma
rm -f constant/geometry/boundaryLayer.obj

#------------------------------------------------------------------------------
