#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy aerofoil surface from resources directory

application="$(getApplication)"

runApplication blockMesh
runApplication transformPoints "scale=(1 0 1)"
runApplication decomposePar
runApplication extrudeMesh

runApplication $application

#------------------------------------------------------------------------------
